[package]
name = "alox-runtime"
version = "0.1.0"
authors = ["Jadon Fowler <j@jadon.io>"]
edition = "2018"

[dependencies]
libloading = "0.6.6"
crossbeam = "0.8"
rayon = "1.5.0"
libc = "0.2"
concache = "0.2.1"
lazy_static = "1.4.0"
